/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './extra-interceptors.module';
import * as import2 from './dialog';
import * as import3 from './ajaxtimeout';
import * as import4 from '../interfaces';
class ExtraInterceptorsModuleInjector extends import0.ɵNgModuleInjector<import1.ExtraInterceptorsModule> {
  _ExtraInterceptorsModule_0:import1.ExtraInterceptorsModule;
  __DialogService_1:import2.DialogService;
  __Interceptor_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _DialogService_1():import2.DialogService {
    if ((this.__DialogService_1 == null)) { (this.__DialogService_1 = new import2.DialogService()); }
    return this.__DialogService_1;
  }
  get _Interceptor_2():any[] {
    if ((this.__Interceptor_2 == null)) { (this.__Interceptor_2 = [
      new import3.AjaxTimeoutInterceptor(this.parent.get(import3.LoginService)),
      new import2.DialogInterceptor(this._DialogService_1)
    ]
    ); }
    return this.__Interceptor_2;
  }
  createInternal():import1.ExtraInterceptorsModule {
    this._ExtraInterceptorsModule_0 = new import1.ExtraInterceptorsModule();
    return this._ExtraInterceptorsModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.ExtraInterceptorsModule)) { return this._ExtraInterceptorsModule_0; }
    if ((token === import2.DialogService)) { return this._DialogService_1; }
    if ((token === import4.Interceptor)) { return this._Interceptor_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ExtraInterceptorsModuleNgFactory:import0.NgModuleFactory<import1.ExtraInterceptorsModule> = new import0.NgModuleFactory<any>(ExtraInterceptorsModuleInjector,import1.ExtraInterceptorsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2lvdmFubmkvUHJvamVjdHMvYXRlbmRlL2FuZ3VsYXItaHR0cC1pbnRlcmNlcHRvci9zcmMvaW50ZXJjZXB0b3JzL2V4dHJhLWludGVyY2VwdG9ycy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9naW92YW5uaS9Qcm9qZWN0cy9hdGVuZGUvYW5ndWxhci1odHRwLWludGVyY2VwdG9yL3NyYy9pbnRlcmNlcHRvcnMvZXh0cmEtaW50ZXJjZXB0b3JzLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
