/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './extra-interceptors.module';
import * as import2 from './dialog';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from './ajaxtimeout';
import * as import5 from '../interfaces';
class ExtraInterceptorsModuleInjector extends import0.NgModuleInjector<import1.ExtraInterceptorsModule> {
  _ExtraInterceptorsModule_0:import1.ExtraInterceptorsModule;
  __DialogService_1:import2.DialogService;
  __Interceptor_2:any[];
  constructor(parent:import3.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _DialogService_1():import2.DialogService {
    if ((this.__DialogService_1 == null)) { (this.__DialogService_1 = new import2.DialogService()); }
    return this.__DialogService_1;
  }
  get _Interceptor_2():any[] {
    if ((this.__Interceptor_2 == null)) { (this.__Interceptor_2 = [
      new import4.AjaxTimeoutInterceptor(this.parent.get(import4.LoginService)),
      new import2.DialogInterceptor(this._DialogService_1)
    ]
    ); }
    return this.__Interceptor_2;
  }
  createInternal():import1.ExtraInterceptorsModule {
    this._ExtraInterceptorsModule_0 = new import1.ExtraInterceptorsModule();
    return this._ExtraInterceptorsModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.ExtraInterceptorsModule)) { return this._ExtraInterceptorsModule_0; }
    if ((token === import2.DialogService)) { return this._DialogService_1; }
    if ((token === import5.Interceptor)) { return this._Interceptor_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ExtraInterceptorsModuleNgFactory:import0.NgModuleFactory<import1.ExtraInterceptorsModule> = new import0.NgModuleFactory(ExtraInterceptorsModuleInjector,import1.ExtraInterceptorsModule);