/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './interceptor.module';
import * as import2 from './interfaces';
import * as import3 from '@angular/http';
import * as import4 from './custom-http';
class InterceptorModuleInjector extends import0.ɵNgModuleInjector<import1.InterceptorModule> {
  _InterceptorModule_0:import1.InterceptorModule;
  __Http_1:any;
  __CustomHttp_2:any;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _Http_1():any {
    if ((this.__Http_1 == null)) { (this.__Http_1 = import1.httpFactory(this.parent.get(import2.Interceptor),this.parent.get(import3.XHRBackend),this.parent.get(import3.RequestOptions))); }
    return this.__Http_1;
  }
  get _CustomHttp_2():any {
    if ((this.__CustomHttp_2 == null)) { (this.__CustomHttp_2 = this._Http_1); }
    return this.__CustomHttp_2;
  }
  createInternal():import1.InterceptorModule {
    this._InterceptorModule_0 = new import1.InterceptorModule();
    return this._InterceptorModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.InterceptorModule)) { return this._InterceptorModule_0; }
    if ((token === import3.Http)) { return this._Http_1; }
    if ((token === import4.CustomHttp)) { return this._CustomHttp_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const InterceptorModuleNgFactory:import0.NgModuleFactory<import1.InterceptorModule> = new import0.NgModuleFactory<any>(InterceptorModuleInjector,import1.InterceptorModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvZ2lvdmFubmkvUHJvamVjdHMvYXRlbmRlL2FuZ3VsYXItaHR0cC1pbnRlcmNlcHRvci9zcmMvaW50ZXJjZXB0b3IubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvZ2lvdmFubmkvUHJvamVjdHMvYXRlbmRlL2FuZ3VsYXItaHR0cC1pbnRlcmNlcHRvci9zcmMvaW50ZXJjZXB0b3IubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
